[build]
publish = "public"
command = "hugo"

[build.environment]
HUGO_VERSION = "0.74.3"

[context.production.environment]
HUGO_ENV = "production"

[[redirects]]
from = "/apple-touch-icon.png"
to = "/meta/apple-touch-icon.png"
status = 200

[[redirects]]
from = "/browserconfig.xml"
to = "/meta/browserconfig.xml"
status = 200

[[redirects]]
from = "/favicon.ico"
to = "/meta/favicon.ico"
status = 200
